apiVersion: v1
data:
  .env: |-
    DB_DSN=mongodb://mongo-0.mongo.default.svc.cluster.local:27017,mongo-1.mongo.default.svc.cluster.local:27017/?replicaSet=rs0
    RMQ_USER=<replace>
    RMQ_PASS=<replace>
    RMQ_HOST=rabbitmq.default.svc.cluster.local
    RMQ_PORT=5672
kind: ConfigMap
metadata:
  name: egcom
